---
title: "parcialprogra"
author: "diego vilca torres"
date: "24/7/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#parte 1
#pregunta 1

#tangente hiperbolica
x<- seq(-10,10,0.5)
y<- (exp((x))^2-1)/(exp((x))^2+1)
plot(x,y,"l")

#derivada de tangente hiperbolica
x<- seq(-10,10,0.5)
y<- (4*(exp((x))^2))/((exp((x))^2)+1)^2
plot(x,y,"l")


#pregunta 3
Peri<-function(a,b,c){
  resultado<- a+b+c
  return(resultado)
}
Peri(4,3,5)

Area<-function(a,b,c){
  resultado<- (((a+b+c)/2)*(((a+b+c)/2)-a)*(((a+b+c)/2)-b)*(((a+b+c)/2)-c))^0.5
  return(resultado)
}
Area(3,5,8)

#pregunta 4
Tc<-function(L,n,i,s){
  resultado<- (7*(L^0.6)*(n^0.6))/((i^0.4)*(s^0.3))
  return(resultado)
}
Tc(3,4,6,8)


#pregunta 5
a1=c(2,5,1)
a2=c(1,-4,-1)
a3=c(3,1,-4)
cbind(a1,a2,a3)
A=cbind(a1,a2,a3)
b1=c(7,-19,4)
cbind(b1)
B=cbind(b1)
inv(A)
inv(A)%*%B

#parte 2

#pregunta 1
install.packages("tidyverse")
library(tidyverse)
install.packages("ggplot2")
library(ggplot2)
install.packages("sf")
library(sf)
install.packages("raster")
library(raster)
library(rgdal)

setwd("C:/R/programacion/parcialprogra")
cuenca<- st_read("uh_datos.shp")
plot(cuenca)
datos<- readOGR(dsn = ".", layer= "uh_datos")
dataN<-datos@data
head(dataN)
dataN %>% 
  group_by(AAA) %>% 
  summarise(promedio_AAA=mean(pcp))

#pregunta 2
library(sf)
library(tidyverse)
este<- c(272841.7, 272893.6, 272892.5, 272913.8, 272911.2, 272837.5)
norte<- c(8666459.9, 8666456.9, 8666446.1, 8666441.5, 8666399.9, 8666407.9)
df <- cbind.data.frame(este, norte)

poligono <-function(df){
   pol <- df %>%
    st_as_sf(coords = c("este", "norte"), crs = 32718) %>%
    summarise(geometry = st_combine(geometry)) %>%
    st_cast("POLY")
  plot(pol)
}
poligono(df)

